# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task2_tableViewWithRx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
  # Pods for Task2_tableViewWithRx

  target 'Task2_tableViewWithRxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Task2_tableViewWithRxUITests' do
    # Pods for testing
  end

end
