# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task123' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
  # Pods for Task123

  target 'Task123Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Task123UITests' do
    # Pods for testing
  end

end
