# Uncomment the next line to define a global platform for your project
 platform :ios, '15.6'

target 'day7Task2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'ReachabilitySwift'
pod 'SDWebImage', '~> 5.0'
  # Pods for day7Task2

end
