# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'


target 'task1_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Kingfisher', '~> 7.0'
  # Pods for task1_MVVM

  target 'task1_MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'task1_MVVMUITests' do
    # Pods for testing
  end

end
