# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'task1Movie1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'ReachabilitySwift'
  # Pods for task1Movie1

  target 'task1Movie1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'task1Movie1UITests' do
    # Pods for testing
  end

end
