# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_Demo1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.8.0'
    pod 'RxCocoa', '6.8.0'
  # Pods for RxSwift_Demo1

  target 'RxSwift_Demo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift_Demo1UITests' do
    # Pods for testing
  end

end
