# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 pod 'SDWebImage', '~> 5.0'
 pod 'Cosmos', '~> 23.0'
target 'Day6task1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Day6task1

  target 'Day6task1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Day6task1UITests' do
    # Pods for testing
  end

end
