# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'task2_MVP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SDWebImage', '~> 5.0'
  # Pods for task2_MVP

  target 'task2_MVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'task2_MVPUITests' do
    # Pods for testing
  end

end
