# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'day5Task2_RegisterUsingWebService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Cosmos', '~> 23.0'
  pod 'SDWebImage', '~> 5.0'
  # Pods for day5Task2_RegisterUsingWebService

  target 'day5Task2_RegisterUsingWebServiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'day5Task2_RegisterUsingWebServiceUITests' do
    # Pods for testing
  end

end
